name: First Workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: macos-latest
    steps:
      - name: Print reading
        run: |
            echo "Hello world"
            echo "Hello Toronto"
            echo "Learning is good"
            echo "je sui un Champion"
      - name: Print goodbye
        run: |
            echo "Goodbye"
            echo "from The Engineer"
